// Pure JS bridge for Flutter dart:js interop.
// Auto-generated by extract_translations.py — do not edit manually.

const VERSION = '__VERSION__';
const BUILD_DATE = '__BUILD_DATE__';
const APP_NAME = 'RustDesk';

// --- Config ---

function generateId() {
  return String(Math.floor(Date.now() / 1000) % 900000 + 100000);
}

function generateUuid() {
  const s = BigInt(Date.now());
  const h = Number((s >> 32n) & 0xFFFFFFFFn).toString(16).padStart(8, '0');
  const m1 = Number((s >> 16n) & 0xFFFFn).toString(16).padStart(4, '0');
  const m2 = Number((s & 0xFFFn) | 0x4000n).toString(16).padStart(4, '0');
  const m3 = Number(((s >> 4n) & 0xFFFn) | 0x8000n).toString(16).padStart(4, '0');
  const lo = Number((s * 0x517cc1b727220a95n) & 0xFFFFFFFFFFFFn).toString(16).padStart(12, '0');
  return `${h}-${m1}-${m2}-${m3}-${lo}`;
}

function bytesToHex(bytes) {
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
}

function hexToBytes(hex) {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  return bytes;
}

let _keyReady = null;

async function generateKeyPair() {
  try {
    const kp = await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']);
    const raw = new Uint8Array(await crypto.subtle.exportKey('raw', kp.publicKey));
    const jwk = await crypto.subtle.exportKey('jwk', kp.privateKey);
    localStorage.setItem('pk', bytesToHex(raw));
    localStorage.setItem('sk_jwk', JSON.stringify(jwk));
  } catch(e) {
    const raw = crypto.getRandomValues(new Uint8Array(32));
    localStorage.setItem('pk', bytesToHex(raw));
    console.warn('[WebBridge] Ed25519 not supported, using random pk');
  }
}

function configInit() {
  if (!localStorage.getItem('id')) localStorage.setItem('id', generateId());
  if (!localStorage.getItem('uuid')) localStorage.setItem('uuid', generateUuid());
  if (!localStorage.getItem('pk')) _keyReady = generateKeyPair();
}

function getPkBytes() {
  const pkHex = localStorage.getItem('pk');
  return pkHex ? hexToBytes(pkHex) : new Uint8Array(0);
}

function detectOs() {
  const ua = navigator.userAgent.toLowerCase();
  if (ua.includes('windows')) return 'windows';
  if (ua.includes('mac') || ua.includes('darwin')) return 'macos';
  if (ua.includes('android')) return 'android';
  if (ua.includes('iphone') || ua.includes('ipad')) return 'ios';
  return 'linux';
}

function isMobileDevice() {
  const ua = navigator.userAgent.toLowerCase();
  return ua.includes('android') || ua.includes('iphone') || ua.includes('ipad');
}

function getApiServer() {
  const api = localStorage.getItem('api-server');
  if (api) return api;
  const rs = localStorage.getItem('custom-rendezvous-server');
  if (rs) {
    const host = rs.split(':')[0];
    return `http://${host}:21114`;
  }
  return 'http://127.0.0.1:21114';
}

function defaultUserOption(key) {
  switch (key) {
    case 'view_style': return isMobileDevice() ? 'adaptive' : 'original';
    case 'scroll_style': return 'scrollauto';
    case 'image_quality': return 'balanced';
    case 'codec-preference': return 'auto';
    default: return '';
  }
}

function storageKey(name, arg) {
  return arg ? `${name}:${arg}` : name;
}

// --- Translations (base64-encoded JSON) ---

let translations = {};
try { translations = JSON.parse(decodeURIComponent(escape(atob('__TRANSLATIONS_DATA__')))); } catch(e) {}

let cachedLang = '';

function resolveLocale(locale) {
  if (!locale) return 'en';
  if (locale.toLowerCase().startsWith('zh')) return 'zh-cn';
  return 'en';
}

function translateText(fallbackLocale, text) {
  if (!cachedLang) {
    cachedLang = localStorage.getItem('option:local:lang') || '';
  }
  const locale = cachedLang || fallbackLocale || 'en';
  const lang = resolveLocale(locale);
  if (lang !== 'en' && translations[lang] && translations[lang][text]) {
    return translations[lang][text];
  }
  if (translations.en && translations.en[text]) {
    return translations.en[text];
  }
  return text;
}

// --- Protobuf encoding for rendezvous protocol ---

// RendezvousMessage oneof field numbers (rendezvous.proto)
const MSG = {
  REGISTER_PEER: 6,
  REGISTER_PEER_RESPONSE: 7,
  PUNCH_HOLE_REQUEST: 8,
  PUNCH_HOLE_SENT: 10,
  PUNCH_HOLE_RESPONSE: 11,
  FETCH_LOCAL_ADDR: 12,
  LOCAL_ADDR: 13,
  CONFIG_UPDATE: 14,
  REGISTER_PK: 15,
  REGISTER_PK_RESPONSE: 16,
  SOFTWARE_UPDATE: 17,
  REQUEST_RELAY: 18,
  RELAY_RESPONSE: 19,
  TEST_NAT_REQUEST: 20,
  TEST_NAT_RESPONSE: 21,
  PEER_DISCOVERY: 22,
  ONLINE_REQUEST: 23,
  ONLINE_RESPONSE: 24,
  KEY_EXCHANGE: 25,
  HEALTH_CHECK: 26,
};

function pbRawTag(field, wireType) {
  const tag = (field << 3) | wireType;
  return field < 16 ? [tag] : pbVarint(tag);
}

function pbString(field, str) {
  const bytes = new TextEncoder().encode(str);
  return new Uint8Array([
    ...pbRawTag(field, 2),
    ...pbVarint(bytes.length),
    ...bytes
  ]);
}

function pbVarint(n) {
  const r = [];
  while (n > 0x7F) { r.push((n & 0x7F) | 0x80); n >>>= 7; }
  r.push(n & 0x7F);
  return r;
}

function pbConcat(...arrays) {
  const total = arrays.reduce((s, a) => s + a.length, 0);
  const r = new Uint8Array(total);
  let o = 0;
  for (const a of arrays) { r.set(a, o); o += a.length; }
  return r;
}

function pbBytes(field, bytes) {
  return new Uint8Array([
    ...pbRawTag(field, 2),
    ...pbVarint(bytes.length),
    ...bytes
  ]);
}

function pbEmbed(field, inner) {
  return pbConcat(
    new Uint8Array(pbRawTag(field, 2)),
    new Uint8Array(pbVarint(inner.length)),
    inner
  );
}

function pbUint32(field, n) {
  return new Uint8Array([
    ...pbRawTag(field, 0),
    ...pbVarint(n)
  ]);
}

function pbBool(field, v) {
  return new Uint8Array([...pbRawTag(field, 0), v ? 1 : 0]);
}

function wrapRendezvous(field, inner) {
  return pbEmbed(field, inner);
}

function parseRendezvousFields(data) {
  const fields = {};
  let pos = 0;
  while (pos < data.length) {
    let tag = 0, shift = 0;
    do { tag |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
    const fieldNum = tag >>> 3, wireType = tag & 7;
    if (wireType === 2) {
      let len = 0; shift = 0;
      do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
      if (!(fieldNum in fields)) fields[fieldNum] = data.slice(pos, pos + len);
      pos += len;
    } else if (wireType === 0) {
      let val = 0; shift = 0;
      do { val |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
      if (!(fieldNum in fields)) fields[fieldNum] = val;
    } else if (wireType === 5) {
      if (!(fieldNum in fields)) fields[fieldNum] = data.slice(pos, pos + 4);
      pos += 4;
    } else if (wireType === 1) {
      if (!(fieldNum in fields)) fields[fieldNum] = data.slice(pos, pos + 8);
      pos += 8;
    } else break;
  }
  return fields;
}

function buildOnlineRequest(myId, peers) {
  const inner = pbConcat(pbString(1, myId), ...peers.map(p => pbString(2, p)));
  return wrapRendezvous(MSG.ONLINE_REQUEST, inner);
}

function parseOnlineResponse(data) {
  const f = parseRendezvousFields(data);
  return f[1] || new Uint8Array(0);
}

// --- Message proto field numbers (message.proto) ---
const MSG_MSG = {
  SIGNED_ID: 3,
  PUBLIC_KEY: 4,
  LOGIN_REQUEST: 7,
  LOGIN_RESPONSE: 8,
  HASH: 9,
  PEER_INFO: 25,
};

const DEFAULT_RS_PUB_KEY = 'CtQ3yjQEVuTIVP7tVt4vRS3HJl0RfSLYrwPA8vpU6rw=';

// --- SHA-256 (pure JS) ---
function sha256(data) {
  const K = [
    0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
    0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
    0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
    0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
    0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
    0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
    0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
  ];
  let h0=0x6a09e667,h1=0xbb67ae85,h2=0x3c6ef372,h3=0xa54ff53a;
  let h4=0x510e527f,h5=0x9b05688c,h6=0x1f83d9ab,h7=0x5be0cd19;
  const len = data.length;
  const bitLen = len * 8;
  const padLen = ((56 - (len + 1) % 64) + 64) % 64;
  const buf = new Uint8Array(len + 1 + padLen + 8);
  buf.set(data);
  buf[len] = 0x80;
  const dv = new DataView(buf.buffer);
  dv.setUint32(buf.length - 4, bitLen, false);
  for (let off = 0; off < buf.length; off += 64) {
    const w = new Int32Array(64);
    for (let i = 0; i < 16; i++) w[i] = dv.getInt32(off + i * 4, false);
    for (let i = 16; i < 64; i++) {
      const s0 = (((w[i-15]>>>7)|(w[i-15]<<25)) ^ ((w[i-15]>>>18)|(w[i-15]<<14)) ^ (w[i-15]>>>3))|0;
      const s1 = (((w[i-2]>>>17)|(w[i-2]<<15)) ^ ((w[i-2]>>>19)|(w[i-2]<<13)) ^ (w[i-2]>>>10))|0;
      w[i] = (w[i-16] + s0 + w[i-7] + s1)|0;
    }
    let a=h0,b=h1,c=h2,d=h3,e=h4,f=h5,g=h6,h=h7;
    for (let i = 0; i < 64; i++) {
      const S1 = ((e>>>6)|(e<<26)) ^ ((e>>>11)|(e<<21)) ^ ((e>>>25)|(e<<7));
      const ch = (e & f) ^ (~e & g);
      const t1 = (h + S1 + ch + K[i] + w[i])|0;
      const S0 = ((a>>>2)|(a<<30)) ^ ((a>>>13)|(a<<19)) ^ ((a>>>22)|(a<<10));
      const t2 = (S0 + ((a&b)^(a&c)^(b&c)))|0;
      h=g; g=f; f=e; e=(d+t1)|0; d=c; c=b; b=a; a=(t1+t2)|0;
    }
    h0=(h0+a)|0; h1=(h1+b)|0; h2=(h2+c)|0; h3=(h3+d)|0;
    h4=(h4+e)|0; h5=(h5+f)|0; h6=(h6+g)|0; h7=(h7+h)|0;
  }
  const r = new Uint8Array(32);
  const rv = new DataView(r.buffer);
  rv.setInt32(0,h0,false); rv.setInt32(4,h1,false);
  rv.setInt32(8,h2,false); rv.setInt32(12,h3,false);
  rv.setInt32(16,h4,false); rv.setInt32(20,h5,false);
  rv.setInt32(24,h6,false); rv.setInt32(28,h7,false);
  return r;
}

// --- Crypto helpers (tweetnacl) ---
function b64decode(s) {
  const bin = atob(s);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

function getRsPk() {
  const key = localStorage.getItem('key') || DEFAULT_RS_PUB_KEY;
  return b64decode(key);
}

function getNonce(seqnum) {
  const nonce = new Uint8Array(24);
  const view = new DataView(nonce.buffer);
  view.setUint32(0, Number(seqnum & 0xFFFFFFFFn), true);
  view.setUint32(4, Number((seqnum >> 32n) & 0xFFFFFFFFn), true);
  return nonce;
}

function getRendezvousWsUrl() {
  const api = getApiServer();
  const rs = localStorage.getItem('custom-rendezvous-server');
  let host, wsPort, secure;

  if (api && api !== 'http://127.0.0.1:21114') {
    try {
      const url = new URL(api);
      host = url.hostname;
      wsPort = parseInt(url.port) || (url.protocol === 'https:' ? 443 : 80);
      secure = url.protocol === 'https:';
    } catch(e) { return null; }
  } else if (rs) {
    const parts = rs.split(':');
    host = parts[0];
    const rzPort = parseInt(parts[1]) || 21116;
    wsPort = rzPort + 2;
    secure = false;
  } else {
    return null;
  }

  return `${secure ? 'wss' : 'ws'}://${host}:${wsPort}/ws/id`;
}

function fireOnlineCallback(onlines, offlines) {
  const evt = JSON.stringify({
    name: 'callback_query_onlines',
    onlines: onlines.join(','),
    offlines: offlines.join(',')
  });
  setTimeout(() => { if (typeof window.onRegisteredEvent === 'function') window.onRegisteredEvent(evt); }, 0);
}

// --- Online status query via WebSocket ---

function queryOnlines(value) {
  let ids = [];
  try { ids = JSON.parse(value || '[]'); } catch(e) { return; }
  if (!ids.length) return;

  const wsUrl = getRendezvousWsUrl();
  if (!wsUrl) { fireOnlineCallback([], ids); return; }

  const myId = localStorage.getItem('id') || '';
  const msg = buildOnlineRequest(myId, ids);

  const ws = new WebSocket(wsUrl);
  ws.binaryType = 'arraybuffer';

  const timeout = setTimeout(() => {
    ws.close();
    fireOnlineCallback([], ids);
  }, 5000);

  ws.onopen = () => ws.send(msg);

  ws.onmessage = (e) => {
    clearTimeout(timeout);
    ws.close();
    const data = new Uint8Array(e.data);
    try {
      // RendezvousMessage wrapper: field 24 = online_response
      // Tag: (24 << 3) | 2 = 194 = 0xC2, 0x01
      let pos = 0;
      while (pos < data.length) {
        let tag = 0, shift = 0;
        do { tag |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
        const fieldNum = tag >>> 3, wireType = tag & 7;
        if (fieldNum === 24 && wireType === 2) {
          let len = 0; shift = 0;
          do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
          const states = parseOnlineResponse(data.slice(pos, pos + len));
          const onlines = [], offlines = [];
          for (let i = 0; i < ids.length; i++) {
            const bit = 0x01 << (7 - i % 8);
            (states[(i / 8) | 0] & bit) ? onlines.push(ids[i]) : offlines.push(ids[i]);
          }
          fireOnlineCallback(onlines, offlines);
          return;
        } else if (wireType === 2) {
          let len = 0; shift = 0;
          do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
          pos += len;
        } else if (wireType === 0) {
          while (data[pos++] & 0x80) {}
        } else break;
      }
      fireOnlineCallback([], ids);
    } catch(err) {
      console.error('[WebBridge] parse online response error:', err);
      fireOnlineCallback([], ids);
    }
  };

  ws.onerror = () => {
    clearTimeout(timeout);
    fireOnlineCallback([], ids);
  };
}

// --- Session: Rendezvous + Relay connection ---

let sessionState = {
  rzWs: null,
  relayWs: null,
  peerId: '',
  connType: 0,
  uuid: '',
  relayServer: '',
  signedIdPk: null,
  signPk: null,
  password: '',
  isFileTransfer: false,
  isViewCamera: false,
  isTerminal: false,
  closed: false,
  rzTimeout: null,
  relayTimeout: null,
  rzRegWs: null,
  rzRegTimeout: null,
  sessionKey: null,
  encSeqSend: 0n,
  encSeqRecv: 0n,
  secured: false,
  hashSalt: '',
  hashChallenge: '',
  loginPassword: ''
};

function getRelayWsUrl(relayServer) {
  const api = getApiServer();
  const url = new URL(api);
  const secure = url.protocol === 'https:';
  if (relayServer) {
    const parts = relayServer.split(':');
    const host = parts[0];
    return `${secure ? 'wss' : 'ws'}://${host}:${url.port}/ws/relay`;
  } else {
    return `${secure ? 'wss' : 'ws'}://${url.hostname}:${url.port}/ws/relay`;
  }
}

function fireSessionEvent(name, data) {
  const evt = JSON.stringify({ name: name, data: typeof data === 'string' ? data : JSON.stringify(data) });
  setTimeout(() => { if (typeof window.onRegisteredEvent === 'function') window.onRegisteredEvent(evt); }, 0);
}

function sessionFail(reason) {
  console.error('[WebBridge] session fail:', reason);
  const evt = JSON.stringify({ name: 'msgbox', type: 'error', title: 'Connection Error', text: reason, link: '' });
  setTimeout(() => {
    if (typeof window.onGlobalEvent === 'function') window.onGlobalEvent(evt);
    else if (typeof window.onRegisteredEvent === 'function') window.onRegisteredEvent(evt);
  }, 0);
  closeSession();
}

function closeSession() {
  sessionState.closed = true;
  if (sessionState.rzTimeout) { clearTimeout(sessionState.rzTimeout); sessionState.rzTimeout = null; }
  if (sessionState.relayTimeout) { clearTimeout(sessionState.relayTimeout); sessionState.relayTimeout = null; }
  if (sessionState.rzRegWs) { try { sessionState.rzRegWs.close(); } catch(e) {} sessionState.rzRegWs = null; }
  if (sessionState.rzRegTimeout) { clearTimeout(sessionState.rzRegTimeout); sessionState.rzRegTimeout = null; }
  if (sessionState.rzWs) { try { sessionState.rzWs.close(); } catch(e) {} sessionState.rzWs = null; }
  if (sessionState.relayWs) { try { sessionState.relayWs.close(); } catch(e) {} sessionState.relayWs = null; }
  sessionState.sessionKey = null;
  sessionState.encSeqSend = 0n;
  sessionState.encSeqRecv = 0n;
  sessionState.secured = false;
  sessionState.signPk = null;
  sessionState.hashSalt = '';
  sessionState.hashChallenge = '';
  sessionState.loginPassword = '';
}

function splitRendezvousMessages(data) {
  const msgs = [];
  let pos = 0;
  while (pos < data.length) {
    const start = pos;
    let tag = 0, shift = 0;
    do { tag |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
    const wireType = tag & 7;
    if (wireType === 2) {
      let len = 0; shift = 0;
      do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
      pos += len;
    } else if (wireType === 0) {
      do {} while (data[pos++] & 0x80);
    } else if (wireType === 5) { pos += 4;
    } else if (wireType === 1) { pos += 8;
    } else break;
    msgs.push(data.slice(start, pos));
  }
  return msgs;
}

function startSessionConnection(peerId, connType, password, isFileTransfer, isViewCamera, isTerminal) {
  closeSession();
  sessionState.closed = false;
  sessionState.peerId = peerId;
  sessionState.connType = connType;
  sessionState.password = password || '';
  sessionState.isFileTransfer = isFileTransfer;
  sessionState.isViewCamera = isViewCamera;
  sessionState.isTerminal = isTerminal;

  const wsUrl = getRendezvousWsUrl();
  console.log('[WebBridge] rendezvous wsUrl:', wsUrl, 'peerId:', peerId);
  if (!wsUrl) { sessionFail('No rendezvous server configured'); return; }

  const ws = new WebSocket(wsUrl);
  ws.binaryType = 'arraybuffer';
  sessionState.rzWs = ws;

  sessionState.rzTimeout = setTimeout(() => {
    sessionFail('Timeout');
  }, 15000);

  ws.onopen = () => {
    console.log('[WebBridge] rendezvous WS connected');
    sendPunchHoleRequest();
  };

  function sendPunchHoleRequest() {
    const key = localStorage.getItem('key') || '';
    const token = localStorage.getItem('option:local:access_token') || '';
    console.log('[WebBridge] PunchHoleRequest key:', key ? key.substring(0, 8) + '...' : '(empty)', 'keyLen:', key.length, 'token:', token ? 'present' : '(empty)');
    const punchInner = pbConcat(
      pbString(1, peerId),
      pbString(3, key),
      pbUint32(4, connType),
      pbString(5, token),
      pbString(6, VERSION),
      pbBool(8, true)
    );
    const punchMsg = wrapRendezvous(MSG.PUNCH_HOLE_REQUEST, punchInner);
    ws.send(punchMsg);
    console.log('[WebBridge] PunchHoleRequest sent, peerId:', peerId, 'bytes:', punchMsg.length);
  }

  ws.onmessage = (e) => {
    const data = new Uint8Array(e.data);
    console.log('[WebBridge] rendezvous WS message, bytes:', data.length, 'first:', Array.from(data.slice(0, Math.min(20, data.length))));
    const msgs = splitRendezvousMessages(data);
    for (const msgData of msgs) {
      if (sessionState.closed) break;
      try {
        const outer = parseRendezvousFields(msgData);
        if (outer[MSG.PUNCH_HOLE_RESPONSE]) {
          clearTimeout(sessionState.rzTimeout);
          const ph = parseRendezvousFields(outer[MSG.PUNCH_HOLE_RESPONSE]);
          const socketAddr = ph[1];
          if (!socketAddr || socketAddr.length === 0) {
            if (ph[7] instanceof Uint8Array && ph[7].length > 0) {
              sessionFail(new TextDecoder().decode(ph[7]));
            } else {
              const failMap = { 0: 'ID does not exist', 2: 'Remote desktop is offline', 3: 'Key mismatch', 4: 'Key overuse' };
              sessionFail(failMap[ph[3]] || 'other punch hole failure');
            }
            break;
          }
          sessionState.relayServer = ph[4] ? new TextDecoder().decode(ph[4]) : '';
          sessionState.signedIdPk = ph[2] || null;
          console.log('[WebBridge] PunchHoleResponse: socketAddr=', socketAddr ? socketAddr.length + ' bytes' : 'null', 'relayServer=', sessionState.relayServer, 'signedIdPk=', sessionState.signedIdPk ? sessionState.signedIdPk.length + ' bytes' : 'null');
          if (sessionState.signedIdPk && sessionState.signedIdPk instanceof Uint8Array && sessionState.signedIdPk.length > 0) {
            try {
              const rsPk = getRsPk();
              const idPkBytes = nacl.sign.open(sessionState.signedIdPk, rsPk);
              if (idPkBytes) {
                const idPk = parseRendezvousFields(idPkBytes);
                if (idPk[2] && idPk[2].length === 32) {
                  sessionState.signPk = idPk[2];
                  console.log('[WebBridge] signPk extracted from signedIdPk');
                }
              }
            } catch(e) { console.warn('[WebBridge] sign_pk extraction failed:', e); }
          }
          sessionState.uuid = generateUuid();
          registerRelaySession();
        } else if (outer[MSG.RELAY_RESPONSE]) {
          clearTimeout(sessionState.rzTimeout);
          const rr = parseRendezvousFields(outer[MSG.RELAY_RESPONSE]);
          const refuse = rr[6];
          if (refuse instanceof Uint8Array && refuse.length > 0) {
            sessionFail(new TextDecoder().decode(refuse));
            break;
          }
          if (rr[2] instanceof Uint8Array && rr[2].length > 0) {
            sessionState.uuid = new TextDecoder().decode(rr[2]);
          }
          if (rr[3] instanceof Uint8Array) {
            sessionState.relayServer = new TextDecoder().decode(rr[3]);
          }
          if (rr[5] instanceof Uint8Array) {
            sessionState.signedIdPk = rr[5];
          }
          console.log('[WebBridge] RelayResponse (registration OK), uuid=', sessionState.uuid, 'relayServer=', sessionState.relayServer);
          connectRelay();
        } else if (outer[MSG.REGISTER_PEER_RESPONSE]) {
          const rpr = parseRendezvousFields(outer[MSG.REGISTER_PEER_RESPONSE]);
          const requestPk = rpr[2] && (rpr[2] instanceof Uint8Array ? rpr[2].length > 0 && rpr[2][0] : rpr[2]);
          if (requestPk) {
            (async () => {
              try {
                if (_keyReady) await _keyReady;
                const pkBytes = getPkBytes();
                if (pkBytes.length === 0) { sendPunchHoleRequest(); return; }
                const uuid = localStorage.getItem('uuid') || '';
                const myId = localStorage.getItem('id') || '';
                const regInner = pbConcat(
                  pbString(1, myId),
                  pbBytes(2, hexToBytes(uuid.replace(/-/g, ''))),
                  pbBytes(3, pkBytes)
                );
                ws.send(wrapRendezvous(MSG.REGISTER_PK, regInner));
                console.log('[WebBridge] RegisterPk sent');
              } catch(e) {
                console.warn('[WebBridge] RegisterPk failed:', e);
                sendPunchHoleRequest();
              }
            })();
          } else {
            sendPunchHoleRequest();
          }
        } else if (outer[MSG.REGISTER_PK_RESPONSE]) {
          const rpk = parseRendezvousFields(outer[MSG.REGISTER_PK_RESPONSE]);
          const result = rpk[1];
          if (result && result.length > 0 && result[0] !== 0) {
            console.warn('[WebBridge] RegisterPk failed, result:', result[0]);
          } else {
            console.log('[WebBridge] RegisterPk OK, sending PunchHoleRequest');
            sendPunchHoleRequest();
          }
        } else {
          console.warn('[WebBridge] Unknown rendezvous response, fields:', Object.keys(outer));
        }
      } catch(err) {
        clearTimeout(sessionState.rzTimeout);
        sessionFail('Rendezvous error: ' + err);
        break;
      }
    }
  };

  ws.onerror = (e) => {
    console.error('[WebBridge] rendezvous WS error', e);
    clearTimeout(sessionState.rzTimeout);
    sessionFail('Failed to connect via rendezvous server');
  };

  ws.onclose = (e) => {
    console.log('[WebBridge] rendezvous WS closed, code:', e.code, 'reason:', e.reason);
  };
}

function registerRelaySession() {
  if (sessionState.closed) return;
  const rzUrl = sessionState.rzWs ? sessionState.rzWs.url : null;
  if (!rzUrl) { sessionFail('No rendezvous connection for relay registration'); return; }
  console.log('[WebBridge] registerRelaySession: url=', rzUrl, 'uuid=', sessionState.uuid);
  const ws = new WebSocket(rzUrl);
  ws.binaryType = 'arraybuffer';
  sessionState.rzRegWs = ws;
  sessionState.rzRegTimeout = setTimeout(() => {
    try { ws.close(); } catch(e) {}
    sessionState.rzRegWs = null;
    sessionFail('Timeout');
  }, 15000);
  ws.onopen = () => {
    const key = localStorage.getItem('key') || '';
    const token = localStorage.getItem('option:local:access_token') || '';
    const inner = pbConcat(
      pbString(1, sessionState.peerId),
      pbString(2, sessionState.uuid),
      pbString(4, sessionState.relayServer),
      pbBool(5, true),
      pbString(6, key),
      pbString(8, token)
    );
    ws.send(wrapRendezvous(MSG.REQUEST_RELAY, inner));
    console.log('[WebBridge] Relay registration sent');
  };
  ws.onmessage = (e) => {
    clearTimeout(sessionState.rzRegTimeout);
    const data = new Uint8Array(e.data);
    console.log('[WebBridge] Relay registration response, bytes:', data.length);
    try {
      const outer = parseRendezvousFields(data);
      if (outer[MSG.RELAY_RESPONSE]) {
        const rr = parseRendezvousFields(outer[MSG.RELAY_RESPONSE]);
        const refuse = rr[6];
        if (refuse instanceof Uint8Array && refuse.length > 0) {
          sessionFail(new TextDecoder().decode(refuse));
          return;
        }
        console.log('[WebBridge] Relay registration OK');
        connectRelay();
      }
    } catch(err) {
      sessionFail('Relay registration error: ' + err);
    }
    try { ws.close(); } catch(e) {}
    sessionState.rzRegWs = null;
  };
  ws.onerror = () => {
    console.error('[WebBridge] Relay registration WS error');
    clearTimeout(sessionState.rzRegTimeout);
    sessionFail('Failed to register relay session');
  };
  ws.onclose = () => {
    console.log('[WebBridge] Relay registration WS closed');
  };
}

function connectRelay() {
  if (sessionState.closed) return;
  const relayUrl = getRelayWsUrl(sessionState.relayServer);
  console.log('[WebBridge] connectRelay: relayServer=', sessionState.relayServer, 'relayUrl=', relayUrl);
  if (!relayUrl) { sessionFail('Cannot derive relay URL'); return; }

  const ws = new WebSocket(relayUrl);
  ws.binaryType = 'arraybuffer';
  sessionState.relayWs = ws;

  sessionState.relayTimeout = setTimeout(() => {
    sessionFail('Timeout');
  }, 15000);

  ws.onopen = () => {
    console.log('[WebBridge] relay WS connected');
    const key = localStorage.getItem('key') || '';
    const token = localStorage.getItem('option:local:access_token') || '';
    const inner = pbConcat(
      pbString(1, sessionState.peerId),
      pbString(2, sessionState.uuid || ''),
      pbString(6, key),
      pbUint32(7, sessionState.connType),
      pbString(8, token)
    );
    ws.send(wrapRendezvous(MSG.REQUEST_RELAY, inner));
    console.log('[WebBridge] RequestRelay sent, uuid=', sessionState.uuid || '');
  };

  ws.onmessage = (e) => {
    clearTimeout(sessionState.relayTimeout);
    const data = new Uint8Array(e.data);
    console.log('[WebBridge] relay WS message, bytes:', data.length, 'first:', Array.from(data.slice(0, Math.min(20, data.length))));
    try {
      const outer = parseRendezvousFields(data);
      if (outer[MSG.RELAY_RESPONSE]) {
        const rr = parseRendezvousFields(outer[MSG.RELAY_RESPONSE]);
        const refuse = rr[6];
        if (refuse instanceof Uint8Array && refuse.length > 0) {
          sessionFail('Relay refused: ' + new TextDecoder().decode(refuse));
          return;
        }
        if (rr[2] instanceof Uint8Array) {
          sessionState.relayServer = new TextDecoder().decode(rr[2]);
        }
        if (sessionState.signedIdPk && sessionState.signedIdPk instanceof Uint8Array && sessionState.signedIdPk.length > 0) {
          try {
            const rsPk = getRsPk();
            const idPkBytes = nacl.sign.open(sessionState.signedIdPk, rsPk);
            if (idPkBytes) {
              const idPk = parseRendezvousFields(idPkBytes);
              if (idPk[2] && idPk[2].length === 32) {
                sessionState.signPk = idPk[2];
              }
            }
          } catch(e) { console.warn('[WebBridge] sign_pk extraction failed:', e); }
        }
        console.log('[WebBridge] RelayResponse received, signPk=', sessionState.signPk ? 'extracted' : 'null');
        sessionState.relayTimeout = setTimeout(() => {
          sessionFail('Timeout');
        }, 15000);
      } else {
        handleRelayMessage(data);
      }
    } catch(err) {
      sessionFail('Relay error: ' + err);
    }
  };

  ws.onerror = (e) => {
    console.error('[WebBridge] relay WS error', e);
    clearTimeout(sessionState.relayTimeout);
    sessionFail('Failed to connect via relay server');
  };

  ws.onclose = (e) => {
    console.log('[WebBridge] relay WS closed, code:', e.code, 'reason:', e.reason);
  };
}

function wrapMsg(field, inner) {
  return pbConcat(new Uint8Array(pbRawTag(field, 2)), new Uint8Array(pbVarint(inner.length)), inner);
}

function relaySend(bytes) {
  if (sessionState.secured) {
    sessionState.encSeqSend++;
    const nonce = getNonce(sessionState.encSeqSend);
    sessionState.relayWs.send(nacl.secretbox(bytes, nonce, sessionState.sessionKey));
  } else {
    sessionState.relayWs.send(bytes);
  }
}

function handleRelayMessage(data) {
  try {
    if (sessionState.secured) {
      sessionState.encSeqRecv++;
      const nonce = getNonce(sessionState.encSeqRecv);
      const decrypted = nacl.secretbox.open(data, nonce, sessionState.sessionKey);
      if (!decrypted) {
        console.error('[WebBridge] Decryption failed');
        return;
      }
      data = decrypted;
    }
    const msg = parseRendezvousFields(data);

    if (msg[MSG_MSG.SIGNED_ID]) {
      handleSignedId(msg[MSG_MSG.SIGNED_ID]);
    } else if (msg[MSG_MSG.HASH]) {
      handleHash(msg[MSG_MSG.HASH]);
    } else if (msg[MSG_MSG.LOGIN_RESPONSE]) {
      handleLoginResponse(msg[MSG_MSG.LOGIN_RESPONSE]);
    }
  } catch(e) {
    console.error('[WebBridge] relay message error:', e);
  }
}

function handleSignedId(signedIdBytes) {
  clearTimeout(sessionState.relayTimeout);
  if (!sessionState.signPk) {
    console.warn('[WebBridge] No signPk, falling back to non-secure');
    relaySend(wrapMsg(MSG_MSG.PUBLIC_KEY, new Uint8Array(0)));
    return;
  }
  let idPkBytes;
  try {
    idPkBytes = nacl.sign.open(signedIdBytes, sessionState.signPk);
  } catch(e) {
    console.warn('[WebBridge] Signature verification error, falling back:', e);
    relaySend(wrapMsg(MSG_MSG.PUBLIC_KEY, new Uint8Array(0)));
    return;
  }
  if (!idPkBytes) {
    console.warn('[WebBridge] pk mismatch, falling back to non-secure');
    relaySend(wrapMsg(MSG_MSG.PUBLIC_KEY, new Uint8Array(0)));
    return;
  }
  const idPk = parseRendezvousFields(idPkBytes);
  const peerId = idPk[1] ? new TextDecoder().decode(idPk[1]) : '';
  const theirPkB = idPk[2];
  if (peerId !== sessionState.peerId || !theirPkB || theirPkB.length !== 32) {
    console.warn('[WebBridge] sign failure (id/pk mismatch), falling back to non-secure');
    relaySend(wrapMsg(MSG_MSG.PUBLIC_KEY, new Uint8Array(0)));
    return;
  }
  const kp = nacl.box.keyPair();
  const symKey = nacl.randomBytes(32);
  const nonce = new Uint8Array(32);
  const sealedKey = nacl.box(symKey, nonce, theirPkB, kp.secretKey);
  const pkInner = pbConcat(pbBytes(1, kp.publicKey), pbBytes(2, sealedKey));
  relaySend(wrapMsg(MSG_MSG.PUBLIC_KEY, pkInner));
  sessionState.sessionKey = symKey;
  sessionState.encSeqSend = 0n;
  sessionState.encSeqRecv = 0n;
  sessionState.secured = true;
  console.log('[WebBridge] Encryption enabled');
}

function handleHash(hashBytes) {
  const hf = parseRendezvousFields(hashBytes);
  const salt = hf[1] ? new TextDecoder().decode(hf[1]) : '';
  const challenge = hf[2] ? new TextDecoder().decode(hf[2]) : '';
  sessionState.hashSalt = salt;
  sessionState.hashChallenge = challenge;
  const pwd = sessionState.loginPassword || sessionState.password;
  let hashPwd;
  if (pwd) {
    hashPwd = sha256(new Uint8Array([...sha256(new TextEncoder().encode(pwd)), ...new TextEncoder().encode(salt)]));
    hashPwd = sha256(new Uint8Array([...hashPwd, ...new TextEncoder().encode(challenge)]));
  } else {
    hashPwd = new Uint8Array(0);
  }
  sendLoginRequest(hashPwd);
  if (!pwd) {
    fireSessionEvent('msgbox', JSON.stringify({ type: 'input-password', title: 'Password Required', text: '', link: '' }));
  }
}

function sendLoginRequest(hashPwd) {
  const myId = localStorage.getItem('id') || '';
  const inner = pbConcat(
    pbString(1, sessionState.peerId),
    pbBytes(2, hashPwd),
    pbString(4, myId),
    pbString(11, VERSION)
  );
  let connInner;
  if (sessionState.isFileTransfer) {
    connInner = pbConcat(inner, pbBytes(7, new Uint8Array(0)));
  } else if (sessionState.isViewCamera) {
    connInner = pbConcat(inner, pbBytes(15, new Uint8Array(0)));
  } else if (sessionState.isTerminal) {
    connInner = pbConcat(inner, pbBytes(16, new Uint8Array(0)));
  } else {
    connInner = inner;
  }
  relaySend(wrapMsg(MSG_MSG.LOGIN_REQUEST, connInner));
}

function handleLoginResponse(lrBytes) {
  const lr = parseRendezvousFields(lrBytes);
  if (lr[1] instanceof Uint8Array && lr[1].length > 0) {
    sessionFail(new TextDecoder().decode(lr[1]));
  } else if (lr[2]) {
    console.log('[WebBridge] Login successful');
    fireSessionEvent('callback_msgbox', JSON.stringify({ type: 'info', detail: 'Connected' }));
  }
}

// --- Public API ---

window.init = async function() {
  configInit();
  setTimeout(() => {
    if (typeof window.onInitFinished === 'function') window.onInitFinished();
  }, 0);
};

window.getByName = function(name, arg) {
  name = name || '';
  arg = arg || '';
  try {
    switch (name) {
      case 'version': return VERSION;
      case 'platform': return 'web';
      case 'app-name': return APP_NAME;
      case 'build_date': return BUILD_DATE;
      case 'local_os': return detectOs();
      case 'my_id': return localStorage.getItem('id') || '';
      case 'uuid': return localStorage.getItem('uuid') || '';
      case 'api_server': return getApiServer();
      case 'is_using_public_server':
        return localStorage.getItem('custom-rendezvous-server') ? 'false' : 'true';
      case 'get_conn_status': return '{"status_num":0}';
      case 'fav': return localStorage.getItem('fav') || '[]';
      case 'options': {
        const map = {};
        for (const k of ['custom-rendezvous-server', 'relay-server', 'api-server', 'key']) {
          map[k] = localStorage.getItem(k) || '';
        }
        return JSON.stringify(map);
      }
      case 'langs': return '[["en","English"],["zh-CN","简体中文"]]';
      case 'option:user:default': {
        const v = localStorage.getItem(`option:user:default:${arg}`);
        return (v !== null && v !== '') ? v : defaultUserOption(arg);
      }
      case 'option': return localStorage.getItem(arg) || '';
      case 'translate': {
        try {
          const obj = JSON.parse(arg);
          return translateText(obj.locale || 'en', obj.text || '');
        } catch(e) { return ''; }
      }
      default: return localStorage.getItem(storageKey(name, arg)) || '';
    }
  } catch(e) {
    console.error(`[WebBridge] getByName("${name}") error:`, e);
    return '';
  }
};

window.setByName = function(name, value) {
  name = name || '';
  value = value || '';
  try {
    switch (name) {
      case 'load_ab':
        setTimeout(() => { if (typeof window.onLoadAbFinished === 'function') window.onLoadAbFinished('{}'); }, 0);
        return '';
      case 'load_group':
        setTimeout(() => { if (typeof window.onLoadGroupFinished === 'function') window.onLoadGroupFinished('{}'); }, 0);
        return '';
      case 'query_onlines':
        queryOnlines(value);
        return '';
      case 'session_add_sync': {
        try {
          const obj = JSON.parse(value);
          sessionState.peerId = obj.id || '';
          sessionState.password = obj.password || '';
          sessionState.isFileTransfer = !!obj.isFileTransfer;
          sessionState.isViewCamera = !!obj.isViewCamera;
          sessionState.isTerminal = !!obj.isTerminal;
        } catch(e) {}
        return '';
      }
      case 'session_start': {
        try {
          const obj = JSON.parse(value);
          let ct = 0;
          if (sessionState.isFileTransfer) ct = 1;
          else if (sessionState.isViewCamera) ct = 4;
          else if (sessionState.isTerminal) ct = 5;
          console.log('[WebBridge] session_start:', obj.id, 'ct:', ct, 'peerId:', sessionState.peerId);
          startSessionConnection(obj.id || sessionState.peerId, ct, sessionState.password, sessionState.isFileTransfer, sessionState.isViewCamera, sessionState.isTerminal);
        } catch(e) { console.error('[WebBridge] session_start error:', e); }
        return '';
      }
      case 'login': {
        try {
          const obj = JSON.parse(value);
          sessionState.loginPassword = obj.password || '';
          if (sessionState.hashChallenge && sessionState.secured) {
            const pwd = sessionState.loginPassword;
            let hashPwd = sha256(new Uint8Array([...sha256(new TextEncoder().encode(pwd)), ...new TextEncoder().encode(sessionState.hashSalt)]));
            hashPwd = sha256(new Uint8Array([...hashPwd, ...new TextEncoder().encode(sessionState.hashChallenge)]));
            sendLoginRequest(hashPwd);
          }
        } catch(e) {}
        return '';
      }
      case 'send_2fa': {
        // Phase 3: send 2FA code
        return '';
      }
      case 'session_close':
        console.log('[WebBridge] session_close');
        closeSession();
        return '';
      case 'reconnect': {
        if (sessionState.peerId) {
          let ct = 0;
          if (sessionState.isFileTransfer) ct = 1;
          else if (sessionState.isViewCamera) ct = 4;
          else if (sessionState.isTerminal) ct = 5;
          startSessionConnection(sessionState.peerId, ct, sessionState.password, sessionState.isFileTransfer, sessionState.isViewCamera, sessionState.isTerminal);
        }
        return '';
      }
      case 'option':
      case 'option:local':
      case 'option:flutter:peer':
      case 'option:flutter:local':
      case 'option:user:default':
      case 'envvar': {
        try {
          const obj = JSON.parse(value);
          if (obj.name !== undefined && obj.value !== undefined) {
            const key = name === 'option' ? obj.name : `${name}:${obj.name}`;
            localStorage.setItem(key, obj.value);
          }
        } catch(e) {}
        return '';
      }
      case 'option:toggle': {
        const key = `option:toggle:${value}`;
        const cur = localStorage.getItem(key);
        localStorage.setItem(key, cur === 'true' ? 'false' : 'true');
        return '';
      }
      case 'options': {
        try {
          const obj = JSON.parse(value);
          for (const [k, v] of Object.entries(obj)) {
            if (typeof v === 'string') localStorage.setItem(k, v);
          }
        } catch(e) {}
        return '';
      }
      case 'fav':
      case 'image_quality':
      case 'remember':
        localStorage.setItem(name, value);
        return '';
      default: return '';
    }
  } catch(e) {
    console.error(`[WebBridge] setByName("${name}") error:`, e);
    return '';
  } finally {
    if (name === 'option:local') cachedLang = '';
  }
};

window.isMobile = function() {
  return isMobileDevice();
};
