// Pure JS bridge for Flutter dart:js interop.
// Auto-generated by extract_translations.py — do not edit manually.

const VERSION = '__VERSION__';
const BUILD_DATE = '__BUILD_DATE__';
const APP_NAME = 'RustDesk';

// --- Config ---

function generateId() {
  return String(Math.floor(Date.now() / 1000) % 900000 + 100000);
}

function generateUuid() {
  const s = BigInt(Date.now());
  const h = Number((s >> 32n) & 0xFFFFFFFFn).toString(16).padStart(8, '0');
  const m1 = Number((s >> 16n) & 0xFFFFn).toString(16).padStart(4, '0');
  const m2 = Number((s & 0xFFFn) | 0x4000n).toString(16).padStart(4, '0');
  const m3 = Number(((s >> 4n) & 0xFFFn) | 0x8000n).toString(16).padStart(4, '0');
  const lo = Number((s * 0x517cc1b727220a95n) & 0xFFFFFFFFFFFFn).toString(16).padStart(12, '0');
  return `${h}-${m1}-${m2}-${m3}-${lo}`;
}

function configInit() {
  if (!localStorage.getItem('id')) localStorage.setItem('id', generateId());
  if (!localStorage.getItem('uuid')) localStorage.setItem('uuid', generateUuid());
}

function detectOs() {
  const ua = navigator.userAgent.toLowerCase();
  if (ua.includes('windows')) return 'windows';
  if (ua.includes('mac') || ua.includes('darwin')) return 'macos';
  if (ua.includes('android')) return 'android';
  if (ua.includes('iphone') || ua.includes('ipad')) return 'ios';
  return 'linux';
}

function isMobileDevice() {
  const ua = navigator.userAgent.toLowerCase();
  return ua.includes('android') || ua.includes('iphone') || ua.includes('ipad');
}

function getApiServer() {
  const api = localStorage.getItem('api-server');
  if (api) return api;
  const rs = localStorage.getItem('custom-rendezvous-server');
  if (rs) {
    const host = rs.split(':')[0];
    return `http://${host}:21114`;
  }
  return 'http://127.0.0.1:21114';
}

function defaultUserOption(key) {
  switch (key) {
    case 'view_style': return isMobileDevice() ? 'adaptive' : 'original';
    case 'scroll_style': return 'scrollauto';
    case 'image_quality': return 'balanced';
    case 'codec-preference': return 'auto';
    default: return '';
  }
}

function storageKey(name, arg) {
  return arg ? `${name}:${arg}` : name;
}

// --- Translations (base64-encoded JSON) ---

let translations = {};
try { translations = JSON.parse(decodeURIComponent(escape(atob('__TRANSLATIONS_DATA__')))); } catch(e) {}

let cachedLang = '';

function resolveLocale(locale) {
  if (!locale) return 'en';
  if (locale.toLowerCase().startsWith('zh')) return 'zh-cn';
  return 'en';
}

function translateText(fallbackLocale, text) {
  if (!cachedLang) {
    cachedLang = localStorage.getItem('option:local:lang') || '';
  }
  const locale = cachedLang || fallbackLocale || 'en';
  const lang = resolveLocale(locale);
  if (lang !== 'en' && translations[lang] && translations[lang][text]) {
    return translations[lang][text];
  }
  if (translations.en && translations.en[text]) {
    return translations.en[text];
  }
  return text;
}

// --- Protobuf encoding for rendezvous protocol ---

function pbString(field, str) {
  const bytes = new TextEncoder().encode(str);
  return new Uint8Array([
    (field << 3) | 2,
    ...pbVarint(bytes.length),
    ...bytes
  ]);
}

function pbVarint(n) {
  const r = [];
  while (n > 0x7F) { r.push((n & 0x7F) | 0x80); n >>>= 7; }
  r.push(n & 0x7F);
  return r;
}

function pbConcat(...arrays) {
  const total = arrays.reduce((s, a) => s + a.length, 0);
  const r = new Uint8Array(total);
  let o = 0;
  for (const a of arrays) { r.set(a, o); o += a.length; }
  return r;
}

function buildOnlineRequest(myId, peers) {
  // OnlineRequest: field 1 = id (string), field 2 = peers (repeated string)
  const inner = pbConcat(
    pbString(1, myId),
    ...peers.map(p => pbString(2, p))
  );
  // RendezezvousMessage: field 23 = online_request (field 23, wire type 2 = tag 186)
  return pbConcat(
    new Uint8Array([186, 1]),
    new Uint8Array(pbVarint(inner.length)),
    inner
  );
}

function parseOnlineResponse(data) {
  // OnlineResponse: field 1 = states (bytes)
  let pos = 0;
  while (pos < data.length) {
    let tag = 0, shift = 0;
    do { tag |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
    const fieldNum = tag >>> 3, wireType = tag & 7;
    if (fieldNum === 1 && wireType === 2) {
      let len = 0; shift = 0;
      do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
      return data.slice(pos, pos + len);
    } else if (wireType === 2) {
      let len = 0; shift = 0;
      do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
      pos += len;
    } else if (wireType === 0) {
      while (data[pos++] & 0x80) {}
    } else break;
  }
  return new Uint8Array(0);
}

// --- Online status query via WebSocket ---

function getOnlineWsUrl() {
  const api = getApiServer();
  const rs = localStorage.getItem('custom-rendezvous-server');
  let host, wsPort, secure;

  if (api && api !== 'http://127.0.0.1:21114') {
    try {
      const url = new URL(api);
      host = url.hostname;
      wsPort = parseInt(url.port) || (url.protocol === 'https:' ? 443 : 80);
      secure = url.protocol === 'https:';
    } catch(e) { return null; }
  } else if (rs) {
    const parts = rs.split(':');
    host = parts[0];
    const rzPort = parseInt(parts[1]) || 21116;
    wsPort = rzPort + 2;
    secure = false;
  } else {
    return null;
  }

  return `${secure ? 'wss' : 'ws'}://${host}:${wsPort}/ws/id`;
}

function fireOnlineCallback(onlines, offlines) {
  const evt = JSON.stringify({
    name: 'callback_query_onlines',
    onlines: onlines.join(','),
    offlines: offlines.join(',')
  });
  setTimeout(() => { if (typeof window.onRegisteredEvent === 'function') window.onRegisteredEvent(evt); }, 0);
}

function queryOnlines(value) {
  let ids = [];
  try { ids = JSON.parse(value || '[]'); } catch(e) { return; }
  if (!ids.length) return;

  const wsUrl = getOnlineWsUrl();
  if (!wsUrl) { fireOnlineCallback([], ids); return; }

  const myId = localStorage.getItem('id') || '';
  const msg = buildOnlineRequest(myId, ids);

  const ws = new WebSocket(wsUrl);
  ws.binaryType = 'arraybuffer';

  const timeout = setTimeout(() => {
    ws.close();
    fireOnlineCallback([], ids);
  }, 5000);

  ws.onopen = () => ws.send(msg);

  ws.onmessage = (e) => {
    clearTimeout(timeout);
    ws.close();
    const data = new Uint8Array(e.data);
    try {
      // RendezvousMessage wrapper: field 24 = online_response
      // Tag: (24 << 3) | 2 = 194 = 0xC2, 0x01
      let pos = 0;
      while (pos < data.length) {
        let tag = 0, shift = 0;
        do { tag |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
        const fieldNum = tag >>> 3, wireType = tag & 7;
        if (fieldNum === 24 && wireType === 2) {
          let len = 0; shift = 0;
          do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
          const states = parseOnlineResponse(data.slice(pos, pos + len));
          const onlines = [], offlines = [];
          for (let i = 0; i < ids.length; i++) {
            const bit = 0x01 << (7 - i % 8);
            (states[(i / 8) | 0] & bit) ? onlines.push(ids[i]) : offlines.push(ids[i]);
          }
          fireOnlineCallback(onlines, offlines);
          return;
        } else if (wireType === 2) {
          let len = 0; shift = 0;
          do { len |= (data[pos] & 0x7F) << shift; shift += 7; } while (data[pos++] & 0x80);
          pos += len;
        } else if (wireType === 0) {
          while (data[pos++] & 0x80) {}
        } else break;
      }
      fireOnlineCallback([], ids);
    } catch(err) {
      console.error('[WebBridge] parse online response error:', err);
      fireOnlineCallback([], ids);
    }
  };

  ws.onerror = () => {
    clearTimeout(timeout);
    fireOnlineCallback([], ids);
  };
}

// --- Public API ---

window.init = async function() {
  configInit();
  setTimeout(() => {
    if (typeof window.onInitFinished === 'function') window.onInitFinished();
  }, 0);
};

window.getByName = function(name, arg) {
  name = name || '';
  arg = arg || '';
  try {
    switch (name) {
      case 'version': return VERSION;
      case 'platform': return 'web';
      case 'app-name': return APP_NAME;
      case 'build_date': return BUILD_DATE;
      case 'local_os': return detectOs();
      case 'my_id': return localStorage.getItem('id') || '';
      case 'uuid': return localStorage.getItem('uuid') || '';
      case 'api_server': return getApiServer();
      case 'is_using_public_server':
        return localStorage.getItem('custom-rendezvous-server') ? 'false' : 'true';
      case 'get_conn_status': return '{"status_num":0}';
      case 'fav': return localStorage.getItem('fav') || '[]';
      case 'options': {
        const map = {};
        for (const k of ['custom-rendezvous-server', 'relay-server', 'api-server', 'key']) {
          map[k] = localStorage.getItem(k) || '';
        }
        return JSON.stringify(map);
      }
      case 'langs': return '[["en","English"],["zh-CN","简体中文"]]';
      case 'option:user:default': {
        const v = localStorage.getItem(`option:user:default:${arg}`);
        return (v !== null && v !== '') ? v : defaultUserOption(arg);
      }
      case 'option': return localStorage.getItem(arg) || '';
      case 'translate': {
        try {
          const obj = JSON.parse(arg);
          return translateText(obj.locale || 'en', obj.text || '');
        } catch(e) { return ''; }
      }
      default: return localStorage.getItem(storageKey(name, arg)) || '';
    }
  } catch(e) {
    console.error(`[WebBridge] getByName("${name}") error:`, e);
    return '';
  }
};

window.setByName = function(name, value) {
  name = name || '';
  value = value || '';
  try {
    switch (name) {
      case 'load_ab':
        setTimeout(() => { if (typeof window.onLoadAbFinished === 'function') window.onLoadAbFinished('{}'); }, 0);
        return '';
      case 'load_group':
        setTimeout(() => { if (typeof window.onLoadGroupFinished === 'function') window.onLoadGroupFinished('{}'); }, 0);
        return '';
      case 'query_onlines':
        queryOnlines(value);
        return '';
      case 'option':
      case 'option:local':
      case 'option:flutter:peer':
      case 'option:flutter:local':
      case 'option:user:default':
      case 'envvar': {
        try {
          const obj = JSON.parse(value);
          if (obj.name !== undefined && obj.value !== undefined) {
            const key = name === 'option' ? obj.name : `${name}:${obj.name}`;
            localStorage.setItem(key, obj.value);
          }
        } catch(e) {}
        return '';
      }
      case 'option:toggle': {
        const key = `option:toggle:${value}`;
        const cur = localStorage.getItem(key);
        localStorage.setItem(key, cur === 'true' ? 'false' : 'true');
        return '';
      }
      case 'options': {
        try {
          const obj = JSON.parse(value);
          for (const [k, v] of Object.entries(obj)) {
            if (typeof v === 'string') localStorage.setItem(k, v);
          }
        } catch(e) {}
        return '';
      }
      case 'fav':
      case 'image_quality':
      case 'remember':
        localStorage.setItem(name, value);
        return '';
      default: return '';
    }
  } catch(e) {
    console.error(`[WebBridge] setByName("${name}") error:`, e);
    return '';
  } finally {
    if (name === 'option:local') cachedLang = '';
  }
};

window.isMobile = function() {
  return isMobileDevice();
};
